version: "3.8"
services:
  db:
    image: postgres:latest
    expose:
      - 5432
    env_file: .env
    ports:
      - 5431:5432
    volumes:
      - "./data:/var/lib/postgresql/data"
  myapp:
    container_name: myapp
    image: myserver
    env_file: .env
    depends_on:
      - db
    expose:
      - 4000
    volumes:
      - /home/emil/Desktop/pet/server:/conv22/src/app
      - /conv22/src/app/node_modules
    ports:
      - 4000:4000
